name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build $GITHUB_WORKSPACE --file $GITHUB_WORKSPACE/Dockerfile --tag scrapyd_mod:$(date +%s)
